version: '2'
services:
  builder:
    build: .
    image: go-kubectx-builder
    entrypoint: /usr/local/go/bin/go
    command: build -v
    volumes:
      - ./output:/go-kubectx/output
    environment:
      GOOS:
      GOARCH: